services:
  db:
    image: postgres:9.5.25
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - x_db_data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    depends_on:
      - db

volumes:
  x_db_data:
    driver: local