services:
  db:
    image: postgres:9.5.25
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=0258
      - POSTGRES_USER=mirelle
      - POSTGRES_DB=mais.leitura
    volumes:
      - db_data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    depends_on:
      - db

volumes:
  db_data:
    driver: local